services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:9e2eb8ac6d7d55e4add44f27c0103f8171a9b50068496df2344008b50e55e0e8
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
