services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:0a1d041bbd52bd392940dfa5ad0303970455fdadc729b6d7b92f3c230cb4747d
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
