services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:d20c2c11368723489d7eb5c5415782d582e72f600f842c2a6c86290d190948cd
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
