services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:1136b972d256a478984ba6770045a27329d36ad48d492671fda103dc8305a463
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
