services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:58250a1871ea2efac7f1335b057ff649cc733b44291162ed2ae458f32e0a7755
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
